[project]
name = "focusseeds"
version = "0.1.0"
authors = [
  { name="Simon Piechutowski", email="szymonpiechutowski@gmail.com" },
]
dependencies = [
    "textual~=0.71.0",
]
description = "Grow seeds that matter."
readme = "readme.md"
requires-python = ">=3.12"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "textual-dev~=1.5.1",
]

[project.urls]
Homepage = "https://github.com/Zimzozaur/FocusSeeds-TUI"
Issues = "https://github.com/Zimzozaur/FocusSeeds-TUI/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
paths = ["src/focusseeds/static/**"]

[tool.hatch.build.targets.wheel]
paths = ["src/focusseeds/static/**"]

[project.scripts]
Focus-Seeds = "focusseeds.__main__:main"
